---
- hosts: webserver
  become: yes
  tasks:
  - name: this will update 
    apt:
      update_cache: yes 
  - name: this will install apache
    apt:
      name: 
        - apache2
      state: present
