---
- hosts: webserver 
  become: yes
  tasks:
  - apt:
      name: "{{ packagename }}"
      state: present
      update_cache: yes
    notify: 
      - restart tomcat
  - copy:
      src: /home/ansible/playbook/apache.yml
      dest: "{{ destcopy }}"
    notify: 
      - restart tomcat

  handlers:
    - name: restart tomcat
      service:
        name: "{{ packagename }}"
        state: restarted
