---
- hosts: webserver
  become: yes
  tasks:
  - name: basic template with no dynamic content
    template:
      src: basic.j2
      dest: /home/ansible/basic
    template:
      src: second.j2
      dest: /home/ansible/second
