---
# tasks file for apache
- name: installing apache on ubuntu
  apt:
    name: apache2
    state: present
  when: anssible_os_family == "Debian"
- name: installing apche on redhat
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
- notify:
    - restart httpd